### ISSUE TITLE
kubernetes yaml installation. Login prompt configuration error

### ISSUE THREAD

**Issue by xinghui-hou** [netsil/manifests#72]
#### The container creates and runs the figure
![image](https://user-images.githubusercontent.com/10824788/31753498-94f3c432-b456-11e7-8a54-6c4f3d773507.png)
#### kubernetes svc configuration is also normal
![image](https://user-images.githubusercontent.com/10824788/31753576-087a5402-b457-11e7-9df7-a0454093b07a.png)

#### But the page login installation error

![image](https://user-images.githubusercontent.com/10824788/31753390-e42ca312-b455-11e7-869a-4619c7ed62d6.png)

`{"error":{"message":"Validation error","stack":"SequelizeUniqueConstraintError: Validation error\n at Query.formatError (/opt/netsil/user-persistence/node_modules/sequelize/lib/dialects/mysql/query.js:149:14)\n at Query.<anonymous> (/opt/netsil/user-persistence/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)\n at bound (domain.js:280:14)\n at Query.runBound [as _callback] (domain.js:293:12)\n at Query.Sequence.end (/opt/netsil/user-persistence/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)\n at Query.ErrorPacket (/opt/netsil/user-persistence/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)\n at Protocol._parsePacket (/opt/netsil/user-persistence/node_modules/mysql/lib/protocol/Protocol.js:279:23)\n at Parser.write (/opt/netsil/user-persistence/node_modules/mysql/lib/protocol/Parser.js:76:12)\n at Protocol.write (/opt/netsil/user-persistence/node_modules/mysql/lib/protocol/Protocol.js:39:16)\n at Socket.<anonymous> (/opt/netsil/user-persistence/node_modules/mysql/lib/Connection.js:103:28)\n at emitOne (events.js:96:13)\n at Socket.emit (events.js:188:7)\n at readableAddChunk (_stream_readable.js:176:18)\n at Socket.Readable.push (_stream_readable.js:134:10)\n at TCP.onread (net.js:547:20)"},"statusCode":500}`

**Comment by smb06** [comment]
Hi @xinghui-hou, this is from an single-container version that has been deprecated. You can sign up for Netsil Cloud here: https://login.netsil.com/#/signup

Then you don't need to worry about the Netsil installation and will only need to install the collectors.

**Comment by xinghui-hou** [comment]
Then please, our collecotrs in the internal network, or we want to build our own private cloud. How to deal with it
